const deliverablesData = [
  {
    title: 'Week 1',
    data: [
      {
        id: 1,
        title: 'Value vs Reference',
        dueDate: '11/9/2020',
        completed: false,
        percentage: 0,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: 0
      },
      {
        id: 2,
        title: 'Scope & Closures',
        dueDate: '11/10/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 5,
        timeLimit: 10,
        numOfAttempts: 3,
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 3,
        title: 'Keyword "this"',
        dueDate: '11/11/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 4,
        title: 'Classes',
        dueDate: '11/11/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 5,
        title: 'Prototypes',
        dueDate: '11/12/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 6,
        title: 'Keyword "new"',
        dueDate: '11/13/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      }
    ]
  },
  {
    title: 'Week 2',
    data: [
      {
        id: 7,
        title: 'Function Binding',
        dueDate: '11/16/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null
      },
      {
        id: 8,
        title: 'Code Reuse II Review',
        dueDate: '11/17/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 9,
        title: 'JavaScript Callbacks',
        dueDate: '11/18/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 10,
        title: 'Classes',
        dueDate: '11/19/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 11,
        title: 'Order of Execution',
        dueDate: '11/20/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 12,
        title: 'Big O',
        dueDate: '11/20/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      }
    ]
  },
  {
    title: 'Week 3',
    data: [
      {
        id: 13,
        title: 'Data Structures',
        dueDate: '11/23/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 14,
        title: 'Instantiation',
        dueDate: '11/24/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 15,
        title: 'Inheritance Patterns',
        dueDate: '11/25/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 16,
        title: 'ES6',
        dueDate: '11/26/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 17,
        title: 'Recursion',
        dueDate: '11/27/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      }
    ]
  },
  {
    title: 'Week 4',
    data: [
      {
        id: 18,
        title: 'RESTful Practices',
        dueDate: '11/30/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 19,
        title: 'CRUD Operations',
        dueDate: '12/1/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 20,
        title: 'Variables vs Values',
        dueDate: '12/2/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 21,
        title: 'Object-Oriented Programming',
        dueDate: '12/3/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      },
      {
        id: 22,
        title: 'Subclasses',
        dueDate: '12/4/2020',
        completed: false,
        percentage: null,
        numOfQuestions: 10,
        timeLimit: null,
        numOfAttempts: 'unlimited',
        description: "This assessment contains multiple choice challenges. Answer as many questions as possible and submit the entire assessment at once when you're done.",
        numOfCorrect: null,
      }
    ]
  }
]

export default deliverablesData;